### ISSUE TITLE
online map tile usage is not expected and is a privacy leak - should be configurable

### ISSUE THREAD

**Issue by gdt** [openbmap/android#153] opened 2016-05-05 21:45 UTC
I gather from #92 that if there is no map, online tiles from someplace will be used.  This really surprised me, and it's a privacy leak to request nearby tiles.

So, there should be a toggle for online/offline (perhaps online can just be the first choice in the "select map" dialog, along with "none", and the app should default to "none" when first installed.

**Comment by wish7code** [comment] 2016-05-06 12:03
You're right.

I realized this behaviour is problematic for another reason too: it may use significant data volume in background and as such shouldn't be the default behaviour. The reason is the way Android handles tabs. Even when the tab is in background, Android tries to 'cache' the layout. User doesn't see the map at that point and hasn't willingly chosen online usage, but Android downloads tiles nevertheless. This I consider unexpected behaviour too.

Will change with the next release..

BTW, it's mapquest tiles..

**Comment by wish7code** [comment] 2016-09-25 19:17
Fixed with 0.8.18

**Closed by wish7code** 2016-09-25 19:17 UTC
